cfrg/draft-irtf-cfrg-opaque

draft-irtf-cfrg-opaque.md

Fixed typo in K3dh definition

---

draft-irtf-cfrg-opaque.md

Apply Hugo's changes.

---

draft-irtf-cfrg-opaque.md

Address Eric's comments.

---

draft-irtf-cfrg-opaque.md

This change shuffles around content and replaces the text-based protocol descriptions with protocol flows and messages. It also includes a first cut at wire format details for these messages. (We can always iterate later on!) 
cc @hugokraw

Initial draft of wire format messages

---

draft-irtf-cfrg-opaque.md

Generate nonces randomly.

---

draft-irtf-cfrg-opaque.md

Add HMQV key derivation changes.

---

draft-irtf-cfrg-opaque.md

This is to match the VOPRF document, which uses Serialize/Deserialize. (Encode was also used as a type of Hash in hash-to-curve, so this is probably better.)

Replace Encode/Decode with Serialize/Deserialize.

---

draft-irtf-cfrg-opaque.md

This moves derivation of the KdKey to the main protocol flow (outside of the RKR-AEAD algorithm), uses HKDF-Extract for secret derivation, and renames KdKey to exporter_key.

Fix and relocate KdKey derivation.

---

draft-irtf-cfrg-opaque.md

Mostly addressing some minor grammar fixes and typos that I found during my pass.
I also renamed "xcript2", "xcript3" to "transcript2" and "transcript3", feel free to push back on that.
I noticed also that in some places it is referred to as "xcript2" and others it is "xscript2", at the very least those should be made consistent.

Addressing minor grammar and typo fixes

---

draft-irtf-cfrg-opaque.md

We should wrap the Harden() call with an HKDF-Extract call, since there is no guarantee that Harden will output pseudorandom bits
Also changed "exporter key" to read simply as "export key"

Exporter -> export, adding HKDF-Extract around Harden call

---

draft-irtf-cfrg-opaque.md

Recommend a particular encoding policy for skU, pkS, and IdS.

---

draft-irtf-cfrg-opaque.md

And use it to control the auth_key and exporter_key size(s).

Add a hash function dependency

---

draft-irtf-cfrg-opaque.md

This shuffles text around and fixes some lingering issues. I'll do a full pass over the text after we merge this (or some variant of it)!

Restructure the document

---

draft-irtf-cfrg-opaque.md

Address Eric Crockett's review comments.

---

draft-irtf-cfrg-opaque.md

Changing envelope representation in CredentialResponse

---

draft-irtf-cfrg-opaque.md

Remove pkS from CredentialResponse

---

draft-irtf-cfrg-opaque.md

cc @kevinlewi, I'll target submission today!

Swap labels, and adopt new OPRF suites.

---

draft-irtf-cfrg-opaque.md

Closes #85. 
cc @kevinlewi, @stef

Remove protocol messages.

---

draft-irtf-cfrg-opaque.md

Update to some minor details of the current VOPRF draft

---

draft-irtf-cfrg-opaque.md

Remove wrapper RequestMetadata type.

---

draft-irtf-cfrg-opaque.md

Closes #100.
cc @hugokraw, @stef

Reference "Partitioning Oracle Attacks" paper.

---

draft-irtf-cfrg-opaque.md

Defines the serialization for the "credential file" (the object that is stored server-side and acts as the user's password file).
Closes #89.

Adding serialization format for credential file

---

draft-irtf-cfrg-opaque.md

87a13127aa3cf0e0ea1d23a9640f06eb18d925fb changed the signature of
`CreateCredentialResponse`.
I also improved upon @kevinlewi's update.
I took the definitions of the OPRF functions and types from
https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html .
I modified them some. Here is the original text for reference:
- SerializedElement and SerializedScalar are serialized representations of
Element and Scalar types of length Ne and Ns, respectively
- SerializeElement(A): A member function of GG that maps a group element A to
a unique byte array buf of fixed length Ne.
- DeserializeElement(buf): A member
function of GG that maps a byte array buf to a group element A, or fails if
the input is not a valid byte representation of an element.
I removed the references to …

Make the online-phase process diagram match function definitions.

---

draft-irtf-cfrg-opaque.md

I also tackled two suggestions in https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/112.

Update headings and hyphenation.

---

draft-irtf-cfrg-opaque.md
poc/opaque.sage
poc/test_opaque_ake.sage

Simplify envelope secret derivation

---

draft-irtf-cfrg-opaque.md

See discussion in #130 
Closes #130

Adding text on export key usage

---

draft-irtf-cfrg-opaque.md

Renaming "user" to "client"

---

draft-irtf-cfrg-opaque.md

Simplify static DH text.

---

draft-irtf-cfrg-opaque.md

Gets rid of the variable-length encoding of the client/server public/private keys, and restricts them to be of a fixed length (denoted by the parameters `Npk` and `Nsk`). Note that `Npk` and `Nsk` are parameters that must be specified for each AKE instantiation -- this gives the flexibility of future AKE instantiations that are PQ to use a larger `Npk` / `Nsk` if necessary.
Closes #121 and #132

Adding Npk / Nsk parameter to fix public/private key sizes

---

draft-irtf-cfrg-opaque.md

Revert AKE MAC pre-hashing back to HASH()

---

draft-irtf-cfrg-opaque.md

clarify export_key client exclusivity

---

draft-irtf-cfrg-opaque.md

Clarify hash function requirements.

---

draft-irtf-cfrg-opaque.md

The credentials structure is not a message of the protocol, thus, it's upto the implementer its storage definition. 
Its content is now split in `server_identity` and `client_identity` variables.
Closes #203

Removing Credentials structure.

---

poc/opaque_common.sage

Fix random generation of test vectors

---

draft-irtf-cfrg-opaque.md

Add application considerations.

---

draft-irtf-cfrg-opaque.md

Fix some errors. Clarify undefined things.

---

draft-irtf-cfrg-opaque.md

Adding implementation considerations section

---

draft-irtf-cfrg-opaque.md

In this comment (https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/214#issuecomment-865220659) of #214 , I said I removed the fake_ prefixes from some variable names. However, I failed to commit some of those changes. This PR fixes the issue.

Fix fake_ prefixes in test vectors

---

draft-irtf-cfrg-opaque.md

Ensure constant-time fake credential response

---

draft-irtf-cfrg-opaque.md

Note TLS wire format syntax.

---

draft-irtf-cfrg-opaque.md

Fix parameter order. Clarify DH value concatenation.

---

draft-irtf-cfrg-opaque.md

Clarify what's stored on the server during registration.

---

draft-irtf-cfrg-opaque.md

Clarify enumeration prevention limitations.

---

draft-irtf-cfrg-opaque.md

Apparently leftover from last PR

fix leftover function parameter

---

draft-irtf-cfrg-opaque.md

Addresses #254 
- define all "external" messages in the protocol overview section

Abstract KEx messages

---

draft-irtf-cfrg-opaque.md

Cite Argon2 RFC.

---

draft-irtf-cfrg-opaque.md

Note that configuration agreement is necessary for the protocol to run.

---

draft-irtf-cfrg-opaque.md
poc/opaque_core.sage

Pin key derivation seed length to 32 bytes.

---

draft-irtf-cfrg-opaque.md

Addresses #242 and moves around some things for clarity.
This PR derives from and depends on #265

Move AKE API to deps section

---

draft-irtf-cfrg-opaque.md

Update masking key description

---

draft-irtf-cfrg-opaque.md

@chris-wood I believe this needs to be updated, correct?

update Cloudflare affiliation name

---

draft-irtf-cfrg-opaque.md

Make Setup phase explicit and indexable.

---

draft-irtf-cfrg-opaque.md

This follows the code https://github.com/cfrg/draft-irtf-cfrg-opaque/blob/master/poc/opaque_core.sage#L65

fix dst in DeriveAuthKeyPair

---

README.md

I think it's nice stealing that from VOPRF

add OPAQUE version for implementations

---

README.md

Hello, for your consideration (relevant files):
https://github.com/aldenml/ecc/blob/master/src/opaque.h
https://github.com/aldenml/ecc/blob/master/src/opaque.c
https://github.com/aldenml/ecc/blob/master/test/test_opaque.c

add a c implementation to readme

---

draft-irtf-cfrg-opaque.md

Drop TripleDHIKM and inline the function instead

---

draft-irtf-cfrg-opaque.md

Closes #253.
cc @hugokraw for awareness

Promote enumeration

---

draft-irtf-cfrg-opaque.md

Masking as enumeration prevention

---

draft-irtf-cfrg-opaque.md

This also sharpens the requirement for the MAC, stating that it must be collision resistant. (We missed this before.)
cc @hugokraw

Add more justification

---

README.md

A TypeScript implementation can be found at https://github.com/cloudflare/opaque-ts
which is complaint with published [draft-irtf-cfrg-opaque-07](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-opaque-07).

Add opaque-ts TypeScript library.

---

draft-irtf-cfrg-opaque.md

I found some inconsistencies that needed to be addressed.

fix some artifacts

---

draft-irtf-cfrg-opaque.md

Minor edits that fix grammar, keep consistent wording style, etc.

Minor editorial edits to dependencies section

---

draft-irtf-cfrg-opaque.md

As discussed offline, this will remove the "Authenticated Key Exchange (AKE) Protocol" subsection from the "Cryptographic Dependencies" section. This also means removing the definitions of the subroutines "AuthInit", "AuthResponse", "AuthFinish".
This is also an opportunity to clearly define the structs KE1, KE2, and KE3 in the "AKE Messages" section.
Partially addresses #336, but I think in order to complete #336, we should also re-order the sections in the Online AKE stage slightly, so that we aren't at any point referencing things that haven't yet been defined. This means moving the "Credential Retrieval" subsection up top, followed by "AKE messages", followed by "Client Authentication Functions" and "Server Authentication Functions". Not addressing this reordering in this PR, but will …

Removing AKE deps section and defining KE1/KE2/KE3 structs

---

draft-irtf-cfrg-opaque.md

Fix some bugs point out offline

---

draft-irtf-cfrg-opaque.md

Addresses inconsistencies found in https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/356
Note that we need to slightly change how inner_ke2 works (https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/363), to be done in a follow-up PR.

Fixing return types for AKE and 3DH functions

---

draft-irtf-cfrg-opaque.md

There is an outdated reference in the definition of the `AuthServerRespond` function to an `ike2` parameter.
There used to be a struct called "inner ke2" which was used here. Instead, I am adjusting the parameters passed to the `Preamble` function to just accept the three fields needed to construct the preamble.
This also fixes all calls to `Preamble` to pass the three parameters individually.
Closes #363.

Fixing references to inner_ke2 by adjusting preamble parameters

---

draft-irtf-cfrg-opaque.md

Closes https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/376

Changing recommended config from scrypt to argon2id

---

draft-irtf-cfrg-opaque.md

Closes #393
@hugokraw -- can you please confirm this is correct?

Registration requires integrity

---

draft-irtf-cfrg-opaque.md
poc/opaque_core.sage

Closes #400
Closes #399 
Closes #398 
Closes #394 
Closes #392

Remove KSF parameters and mention config updates

---

draft-irtf-cfrg-opaque.md
poc/opaque_ake.sage
poc/opaque_core.sage
poc/opaque_messages.sage

Return client pk in Recovery functions

---

draft-irtf-cfrg-opaque.md

Addresses https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/376

Restoring scrypt as a recommended configuration

---

draft-irtf-cfrg-opaque.md

"SerializeElement(element): Map input element to a fixed-length byte array buf."
Is it necessary and IETF-standard to name the output value variable?
This function's output is later assigned to other variables such as 
"blinded_message = SerializeElement(blinded_element)" (5.2.1)
Thanks, good catch, removed the "buf" from the sentence.
Not really expecting this to be revised, but mentioning it FTR:
The Expand()/Extract() API is specific to HKDF, and not a standard
crypto primitive API. This precludes the (direct) use of other KDFs than
HKDF. It might have been more "inclusive" to use standard KDF or XOF
APIs. 
"a collision-resistant Message Authentication Code (MAC)"
This is not a cryptographically standard security notion, as a MAC's
security goal is unforgeability. If some collision …

Various edits suggested by JP Aumasson

---

draft-irtf-cfrg-opaque.md

Clarifying the use of multiple client seeds

---

draft-irtf-cfrg-opaque.md

Adding Marta Mularczyk under the Acknowledgments section

Updating acknowledgments
