draft-irtf-cfrg-opaque.md

We address static DH oracle attacks in the security considerations. Nothing to be worried about! :-)

Add 256-bit curve suites.

---

draft-irtf-cfrg-opaque.md

This removes the RKR-AEAD dependency in favor of a simpler OTP-like construction for credential secrecy. It also replaces redundant Extract calls on RwdU with Expand calls (RwdU is already assumed to be the output of a RO). Finally, it removes the `context` parameter from all protocol messages, punting that functionality to applications.

Remove RKR-AEAD dependency.

---

draft-irtf-cfrg-opaque.md

This shuffles content around, mostly.

Move configuration information to separate section.

---

draft-irtf-cfrg-opaque.md

Closes #2.
This removes TLS 1.3 integration details, but keeps the SIGMA-I content. (TLS 1.3 details will go in the TLS document.)

Remove TLS 1.3 integration details.

---

draft-irtf-cfrg-opaque.md

- secret_types must contain at least skU
- cleartext_types may be empty
Therefore, lowering the length requirements of these vectors in RegistrationResponse to be 1 and 0, respectively.
Also updating my email and adding a close bracket

Fixing length requirement typos for RegistrationResponse

---

draft-irtf-cfrg-opaque.md

This aligns the KE instantiations with the core protocol messages, using them where appropriate instead of OPRF1/OPRF2/EnvU etc directly.

Align KE instantiations with the core protocol messages.

---

draft-irtf-cfrg-opaque.md

Making this a parameter seems like too much flexibility, so I suggest we be opinionated and remove it.

Fix the nonce length (Nn) to 32 bytes.

---

draft-irtf-cfrg-opaque.md

Require that the envelope export_key HMAC is checked before using the key

---

draft-irtf-cfrg-opaque.md

We can address private key possession proofs and WebAuthn in a future change!

Clarify that keys must be unique per account.

---

draft-irtf-cfrg-opaque.md

I believe the type of the parameter `data` in `CredentialExtension` should be `opaque`, since there is no `CredentialData` defined anywhere.
Also updating my affiliation

Fixing typo in CredentialExtension definition and updating affiliation

---

draft-irtf-cfrg-opaque.md

Closes #5.
It was somewhat stale, and I'm not sure it adds much to the document.
cc @kevinlewi

Remove the performance considerations section.

---

draft-irtf-cfrg-opaque.md

Clarify base mode variant usage of voprf

---

draft-irtf-cfrg-opaque.md

Points mentioned after discussion from #74 
- Removes the sending of idU in KE1
- Adds clarification text around what idU and idS refers to in the AKE key derivation. By default, they will be taken from the idU and idS specified in the envelope. If they are not specified, then they are taken to be equal to pkU and pkS.
- Also clarify that if pkU is not in the envelope, then it must be computed from skU.

Defining idU and idS in AKE section

---

draft-irtf-cfrg-opaque.md

The OPAQUE wrapper protocol is responsible for transmitting idU from
client to server. OPAQUE does not use it for anything other than password
file lookup.
Closes #88.
cc @kevinlewi, @stef

Move idU to CreateCredentialResponse parameter.

---

draft-irtf-cfrg-opaque.md

See #99.
This defines two modes, `base` and `customIdentifier` for the envelope. The credentials are incorporated in the `SecretCredentials` and `CleartextCredentials` structs,
depending on the mode set by the value of `EnvelopeMode`:
```
enum {
base(1),
customIdentifier(2),
(255)
} EnvelopeMode;
```
The `base` mode defines `SecretCredentials` and `CleartextCredentials` as follows:
```
struct {
opaque skU<1..2^16-1>;
} SecretCredentials;
struct {
opaque pkS<1..2^16-1>;
} CleartextCredentials;
```
The `customIdentifier` mode defines `SecretCredentials` and `CleartextCredentials` as follows:
```
struct {
opaque skU<1..2^16-1>;
} SecretCredentials;
struct {
opaque pkS<1..2^16-1>;
opaque idU<0..2^16-1>;
opaque idS<0..2^16-1>;
} CleartextCredentials;
```
These credentials are embedded into the …

Changing envelope definition to  support two fixed modes

---

draft-irtf-cfrg-opaque.md

I chose to leave the enumeration and restrict its values to in the text. 
As discussed, this also makes pkU/pkS mandatory in the core OPAQUE messages.

Pin envelope mode to base or customIdentifier.

---

draft-irtf-cfrg-opaque.md

There were some inconsistencies in the process diagrams and function definitions.
-----
For example, before this change, the output of CreateCredentialRequest in the process diagram
```
request, blind = CreateCredentialRequest(pwdU)
```
did not match the output of CreateCredentialRequest's function definition:
```
Output:
- request, an CredentialRequest structure
- r, an OPRF Scalar value
```
`r` should be `blind`, which FinalizeRequest takes as input.
-----
In another example, the output of FinalizeRequest in the process diagram
```
record, export_key = FinalizeRequest(pwdU, creds, blind, response)
```
did not match the output of FinalizeRequest's function definition:
```
Output:
- envU, the user's Envelope structure
- export_key, an additional key
```

Make process diagrams match function definitions. 

---

draft-irtf-cfrg-opaque.md

In the steps for functions, we surround multiple output params with
parentheses:
```
Steps:
1. (blind, M) = Blind(pwdU)
2. Create RegistrationRequest request with M
3. Output (request, blind)
```
@crockeea pointed out that we should be consistent. From
https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/112#issuecomment-760522234,
"Be consistent about the use of parens for functions which output multiple
values (see protocol diagrams at top of section 3.2 and at the top of 3.3)".

Surround multiple output params with parentheses in process diagrams.

---

draft-irtf-cfrg-opaque.md

This is a pretty invasive change that tries to better organize the document and protocol description into its two steps: registration and authentication. It also includes more wire format details for the 3DH instantiation, and removes HMQV and SIGMA-I in the process. (We can bring them back in a future change as needed.) The outline now looks like so:
```
1.  Introduction  . . . . . . . . . . . . . . . . . . . . . . . .   3
1.1.  Requirements Notation . . . . . . . . . . . . . . . . . .   5
1.2.  Notation  . . . . . . . . . . . . . . . . . . . . . . . .   5
2.  Cryptographic Protocol and Algorithm Dependencies . . . . . .   6
3.  Offline Registration  . . . . . . . . . . . . . . . . . . . .   7
3.1.  Credential Storage  . . . . . . . . . . . . . . . . . . .   8
3.2.  Registration Messages …
```

Structural refactor

---

draft-irtf-cfrg-opaque.md

@stef, replying to your suggestions in-line below. Please let me know if these adequately address the concerns you brought up! Closes #124 
> > 2OSP and OS2IP: Convert a byte string to and from a non-negative integer as described in {{?RFC8017}}.
> 
> link to https://tools.ietf.org/html/rfc8017#section-4.1 and https://tools.ietf.org/html/rfc8017#section-4.2
> 
> perhaps also note that this is also known as the htons/ntohs functions in POSIX - implementors might find this very helpful!
Added a mention that these can be found in Section 4, but did not add the POSIX references since I could not find a link to them, and these may not be as widely known.
> 
> > kX: An OPRF private key used in role X. For example, kU refers to U's private OPRF key.
> 
> is there any other role besides kU?
Good …

Addressing comments from issue #124

---

draft-irtf-cfrg-opaque.md

- Introduces an `oprf_seed` parameter which must be generated during server setup and persisted across all registration/login requests (similar to `server_private_key`)
- Introduces a `cred_identifier` parameter -- this could be the same as `client_identity`, but does not need to be
- Derives `oprf_key` from `oprf_seed` and `cred_identifier` -- this results in altering `RegistrationResponse` and `CredentialResponse`
- Modifies the "Credential File" section to just store the RegistrationUpload object, while making clear that the `oprf_seed` and `server_private_key` need to be kept around too
- In `FinalizeRequest`, adds a new element `envelope_key` which must be stored as part of a `RegistrationUpload` object
- Reverts the changes described in #120 (PR #126), necessary in order for the …

Addressing client enumeration section with protocol changes

---

draft-irtf-cfrg-opaque.md

After discussions with @chris-wood and @kevinlewi and the thread in #84, this PR is a first sketch of a proposal to address these discussions.
Proposal of new envelope modes
1. **Drop Base/CustomIdentifiers**
CleartextCredentials always contain pks, idu and ids. If not supplied by the client, idu and ids MUST default to the public keys.
2. Introduce two new modes
a. **Internal mode**
The client keys are generated internally from a seed. (also called "seed mode", "encryption-less mode", etc. in different issues and conversations). No encrypted creds in the envelope. Applications are not expected to know how to deal with key generation.
b. **External mode**
The client keys are provided by the application, and OPAQUE encrypts the private key into the encrypted creds in the envelope. …

New Envelope mode proposal including private key derivation from OPRF output

---

draft-irtf-cfrg-opaque.md

- introduce Noe, the serialized element length in the OPRF group
- deleted mention of SerializedScalar, since it's not used
- deleted mention of SerializedElement, since it's not used
- specify OPRF group element lengths in message structures
Closes #179

Consistent format for OPRF group elements

---

draft-irtf-cfrg-opaque.md

Move opaque byte representations to uint8

---

draft-irtf-cfrg-opaque.md

This removes some redundant text, tries to introduce better flow in the document (starting with a protocol overview and then drilling into specific stages), and rearranges some text for (what seems to be) better readability. It's still not perfect, but I think this is an improvement overall.

Editorial pass.

---

draft-irtf-cfrg-opaque.md

I've been studying OPAQUE for the last month or so (and I must say I'm in love with it). Yesterday I was reading the draft and found two statements that looked a little contradictory. 
I sent an email asking if one of them was really an accident and @bytemare (at least I think it was him lol) replied me saying that I was correct and also that you guys were accepting pull requests, so here I am :blush:.
- The first statement is the one that that I sent on the email: this statement at the fourth section, second paragraph:  "OPAQUE allows applications to either provide custom client private and public keys for authentication, or to generate them internally. [...] These two options are defined as the "internal" and "external" modes, respectively. [...]"... I think that "internal mode" would …

Contradictory statements on draft

---

draft-irtf-cfrg-opaque.md

Hi, found this while implementing the protocol. You can always set the value outside, but I think adding this step `state.ke1 = ke1` inside `Start` is very convenient and aligned with the use of `state.ke1` inside `ClientFinalize`.

set state.ke1 in client Start, removed unused ke1 input

---

draft-irtf-cfrg-opaque.md

Adds two items to the deployment considerations section:
- Additional client-side entropy: OPAQUE supports the ability to incorporate the
client identity alongside the password to be input to the OPRF. This provides additional
client-side entropy which can supplement the entropy that should be introduced by the
server during an honest execution of the protocol.
- Client-side authentication of the server: Note that online guessing attacks
(against any Asymmetric PAKE) can be done from both the client side and the server side.
This means that additional checks, such as implementing client-side authentication of
the server, should be considered in a production deployment of OPAQUE.
Closes #264 .

Adding deployment considerations for malicious servers

---

draft-irtf-cfrg-opaque.md

Add security consideration for HSM

---

draft-irtf-cfrg-opaque.md

This list includes notable design differences from the original paper description of OPAQUE made to accommodate the specification. This is done to help track the delta between the protocol which has been analyzed and that which is being specified in CFRG.
cc @hugokraw

Add list of paper<>spec design differences

---

draft-irtf-cfrg-opaque.md

I propose to move the name origin to the intro, where it makes more sense to me than in the notation section

Move up the name meaning

---

draft-irtf-cfrg-opaque.md

Closes #295.
I decided to rename the function from `SerializePublicKey` to `SerializeElement` since the multiplication of the element with the scalar produces another element (not necessarily a "public key").

Adding back definition for SerializeElement

---

poc/opaque_ake.sage

The client is meant to get an export key (in addition to the session key) from the registration flow but `generate_ke3` ignores the export key obtained by calling `core.recover_credentials` so it can't be retrieved. I save it to the instance so it can be retrieved in the same way as the session key.

Expose export key after generating ke3

---

draft-irtf-cfrg-opaque.md
poc/opaque_core.sage
poc/test_opaque_ake.sage

`core.finalize_request` requires a `Credentials` instance which it passes to `core.create_envelope` which uses `idS` and `idU` from it to create `CleartextCredentials`. However, a new client key pair is generated in `core.create_envelope` and used instead of the key pair in the `Credentials` instance.
This makes for rather confusing code where you need to generate a client key pair to create a `Credentials` instance to call `core.finalize_request`, but this is ignored and the record returned contains a different public key.
This was examplified in the `run_test_vector` method in `test_opaque_ake.sage` where on lines 158-160 (now lines 144-146), the public key generated earlier is overwritten with a different one. I have now simplified this test file.
This also brings the proof-of-concept …

`core.finalize_request` shouldn't require `Credentials` instance

---

poc/opaque_ake.sage
poc/test_opaque_ake.sage

With client transcript creation split between `generate_ke1` and `generate_ke3`, extra arguments like `idU`, and `pkU` are required for `generate_ke1`. However, if done entirely in `generate_ke3` then they are only required for `generate_ke3`.
This brings the function arguments in line with the pseudocode in the document. Also, in the document, transcript (preamble) creation is done entirely in `ClientFinalize`: https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#name-3dh-client-functions
Also, this way `pkS` is not required for `generate_ke1` or `generate_ke3` since it is obtained from `core.recover_credentials` in `generate_ke3`.
I can't think of a reason why the transcript creation needs to be split across the functions, but please let me know if there is. I hope you don't …

Match `generate_ke1` and `generate_ke3` API to document

---

README.md

conforms to testvectors before the voprf09 update. proof:
https://github.com/stef/libopaque/blob/master/src/tests/opaque-testvectors.c
has one deviation, did not implement the voprf evaluate function in anticipation of it going back to the original oprf variant. hence the output for that is hardcoded, but will be removed with the vporf09 update.

added libopaque to implementations

---

draft-irtf-cfrg-opaque.md

This change refactors the error and implementation considerations as presented in #314, and also leaves a slot for us to address #312 in a followup change.

Refactor error and implementation considerations

---

draft-irtf-cfrg-opaque.md

This wasn't used anywhere in the spec, so let's remove it.

Remove RecoverPublicKey

---

draft-irtf-cfrg-opaque.md

These were missed previously. I'll update the test vector labels in a followup change.

Remove lingering MHF references

---

draft-irtf-cfrg-opaque.md

As discussed offline, I think this should be kept just as a subroutine, but not a dependency, since it is not defined external to the OPAQUE protocol.

Removing key recovery mechanism from dependencies section

---

draft-irtf-cfrg-opaque.md

This finishes the last portion of #352, in which I wanted to reorder the subsections slightly in the AKE portion to make things more clear.
Before this change, we had the following ordering of subsections in AKE:
"Online Authenticated Key Exchange" main section with protocol description at a high level 
- "Client Authentication Functions" subsection
- "Server Authentication Functions" subsection
- "Credential Retrieval" subsection
- "AKE Protocol"
- "AKE Messages" section, this is where KE1, KE2, KE3 are defined
- "3DH Client Functions" subsection
- "3DH Server Functions" subsection
So the main problem was that the first two subsections, Client/Server Authentication Functions, were outputting messages that were only defined in the "AKE Messages" subsection, which was much later.
This …

Reordering AKE subsections

---

draft-irtf-cfrg-opaque.md

Closes #291.
Adding in formal definitions for `ClientState`, `ServerState`, `ClientAkeState`, and `ServerAkeState`.
Note that for the password field, which can be variable-length, I set the type to `opaque password<1..2^16-1>`, even though this is not a strict requirement. I also set blind to be `opaque blind<1..2^16-1>`. Let me know if these should be changed!

Separates ClientState and ServerState from ClientAkeState and ServerAkeState

---

draft-irtf-cfrg-opaque.md

The url referenced is a signed url that expired (see code below).  I replaced it with a url that  is permanent.  the url does 301 but it 301's to a signed url that is created upon the request
```bash
curl -L -vvv "https://www.whatsapp.com/security/WhatsApp_Security_Encrypted_Backups_Whitepaper.pdf"
*   Trying 157.240.22.53:443...
* TCP_NODELAY set
* Connected to www.whatsapp.com (157.240.22.53) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), …
```

fix expired url signature

---

draft-irtf-cfrg-opaque.md

Closes #369.
Replaces instances of `Ne` with `Nn + Nm`. Thanks for the catch @crockeea!

Removing references to Ne parameter

---

draft-irtf-cfrg-opaque.md

Closes #370.
ccing @stef for pointing out the change and @bytemare as an FYI for the original PR that introduced the string
As stated in the issue, I believe this "internal" string should be omitted. It was introduced in https://github.com/cfrg/draft-irtf-cfrg-opaque/commit/950f2f0586dd03a2b3ffab11008c21a4d0d3f12b back when there was an "external" and "internal" mode for the envelope configuration portion of the protocol. Now that we no longer have those, we should have removed this internal configuration reference, but failed to.

Removing reference to internal mode in configuration strings

---

draft-irtf-cfrg-opaque.md

Closes #371.
See the discussion in #371 for more context. Note that this only changes the prose describing the variable names, and not the variable names themselves.
cc'ing @stef for feedback

Rename "ephemeral key share" to "ephemeral public key"

---

draft-irtf-cfrg-opaque.md

I found this while trying to match the test vectors and following the POC implementation.

change the oprf api server dependency to BlindEvaluate

---

draft-irtf-cfrg-opaque.md

There are two `request` members inside the `KE1` struct. The one that `CreateCredentialResponse()` needs is `credential_request`.

Use the correct request in CreateCredentialResponse

---

.gitmodules
poc/Makefile
poc/opaque_ake.sage

Changes:
- Removes duplicated submodule for h2c. Better to use the one inside the voprf module.
- ~Exports more values to make the Fake case reproducible. No changes on test vectors, just more verbose info for the `Fake=True` cases.~

Fix h2c submodule

---

draft-irtf-cfrg-opaque.md

In #397 , @hugokraw suggested
> I suggest the following edit  (marked in italics)
>
> The authors suggest implementing the OPRF phase as a Threshold OPRF
> {{TOPPSS}}, effectively forcing an attacker to act online or to control at
> least t key shares, where t is the threshold number of shares necessary to
> recombine the secret OPRF key*, and only then be able to* run an offline
> dictionary attack.
This PR adds this.
Moreover, he suggested
> You may or may not comment also in the following point:
If the OPRF servers are separate from the authentication server then
finding all n shares still does not help since you cannot run the dictionary
attack without the server's database.
@hugokraw, do you mean _n_ like in "all shares that have been created" or "a threshold number of shares"?

Add Hugo's suggestion about Thresholding

---

poc/Makefile

Having `setup` as a prerequisite of `pyfiles` (which itself is a prerequisite of `test` and `vectors`) means everytime you do `make test`, `setup` is run too. This means the files from submodules are copied and then have to be re-parsed by sage which really slows everything down.
Any future additions to the makefile will also likely have `pyfiles` as a prerequisite so have this problem too. This is the case for my fork and is causing problems.
The downside is that `make setup` must be run the first time so that the files are copied, but this was the case before the commit on 14th March anyway.

POC Makefile: Don't re-setup every time

---

draft-irtf-cfrg-opaque.md

The term "password file" is not used anywhere else in the spec. Usually it's referred to as `record` and the type is `RegistrationRecord`. To avoid confusion I suggest to change it to `registration record` in this particular place.

replace "password file" with "registration record"

---

draft-irtf-cfrg-opaque.md

Novi Research -> Meta
(They're the same thing, but Novi Research doesn't exist anymore)

Updating klewi's affiliation

---

draft-irtf-cfrg-opaque.md

Editorial:
- Sec 2.1, DeriveKeyPair: maybe assign names to the output of this API? 
It is also unclear what happens with the public key. Is that needed 
anywhere else?
Changed the DeriveKeyPair definition to read:
- DeriveKeyPair(seed, info): Create and output (`sk`, `pk`), consisting of a private and public key derived deterministically from a `seed`` and `info`` parameter, as described in {{OPRF, Section 3.2}}.
The public key is not used in one case (when we compute (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE-DeriveKeyPair")), but it is used for some configurations in the AKE section (for example in 3DH ristretto255: DeriveDiffieHellmanKeyPair(seed): This function is implemented as DeriveKeyPair(seed, "OPAQUE-DeriveDiffieHellmanKeyPair"), where DeriveKeyPair is as specified in {{OPRF, …

Incorporating Julia Hesse's edits

---

draft-irtf-cfrg-opaque.md

Second round of edits from Hugo.
- Pulled out a section for defining random-key robustness for MACs + adding some other notes about it.
- Some clarifications on how the client identity can be transmitted being outside of the scope of the protocol
- Also adding text to implementation safeguards to say that the client identity can be added into the OPRF computation if it is bound to the lifetime of the registration record

RKR MAC section + client identity clarifications

---

draft-irtf-cfrg-opaque.md

From https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/418#issuecomment-1737188161:
- In function GenerateKE3 the value server_public_key is returned from RecoverCredentials, but it's never used in GenerateKE3
Indeed this was a typo, the server_public_key parameter did not need to be output by RecoverCredentials because it is already part of the cleartext_credentials output.
This change removes the output of server_public_key from the RecoverCredentials() function

Removing extraneous output from RecoverCredentials

---

draft-irtf-cfrg-opaque.md

General:
It is clear that the authors have taken the previous comments on board and have made many positive changes. However, some important points from previous discussions remain:
-OPAQUE differs in some fundamental ways from PAKEs, for example, it is not PKI-free in the sense of other PAKEs. It would be good to make this very clear in an introductory section where you outline all the properties of standard PAKEs that are different from OPAQUE, and motivate your choices in each case. This is also very important in the security proof: It is different from the case you cite, and consideration needs to be taken here.
-In my opinion, the effort to make the protocol (and its explanation) as general as possible is harming the potential for safe adoption. It is great that there are three …

Adding in edits from Chloe Martindale

---

draft-irtf-cfrg-opaque.md

added proposal to caveat the server-side registration warning

---

draft-irtf-cfrg-opaque.md

As I was rereading the draft, I saw a couple of mistakes and missing spaces. So I ran the text through a corrector that found some other suggestions.

Some corrections to the text

---

draft-irtf-cfrg-opaque.md

reviewing the document at a whole for the rglc, i notice that registration is consistently referred to as "offline registration" - as the meme goes "You Keep Using That Word, I Do Not Think It Means What You Think It Means". most people understand offline as something that doesn't need a network connection. and with opaque `offline` in the context of `registration` has a much more nuanced and different meaning, which is confusing for the casual reader and implementer. and thus i think there is two options, the more expensive let's explicitly define "offline" in this context (and not mix it up with the other use through out this document in the context of attacks) or simply and cheaply delete the offline adjective from the context of registrations. i think this change eliminates one source …

changed offline registration -> registration

---

draft-irtf-cfrg-opaque.md

only clients use the export_key.

export_key is only used by clients

---

draft-irtf-cfrg-opaque.md

As suggested in https://mailarchive.ietf.org/arch/msg/cfrg/Fxxdbe6sBae9yqTtZfwrGvtAKRQ/, this section is out-of-date and does not need to stay in the draft.

Remove Related Protocols section

---

draft-irtf-cfrg-opaque.md

Closes #442 
Updates references from "draft voprf" to RFC9497
Same with draft hash-to-curve and RFC9380

Update references to published drafts for voprf and h2c

---

draft-irtf-cfrg-opaque.md

From correspondence with Hugo Krawczyk -- let's make it extra clear that OPRF keys must be unique per client (addendum to the security considerations section)

Clarifying the requirement that OPRF keys must be unique per client

---

draft-irtf-cfrg-opaque.md

Resolving a slight wording ambiguity that could be interpreted not the way we intend. Servers should consistently assign one  seed for a client, but across clients, different seeds could be used, so long as they are kept consistent.
Spawned from discussion offline with Hugo Krawczyk who requested this change.

Clarifying wording about multiple seeds per client

---

draft-irtf-cfrg-opaque.md

* Replaced "asymmetric PAKE" with augmented PAKE since "asymmetric PAKE" is incorrect terminology.
* Added info on doubly augmented PAKEs (dPAKE).
* Stated OPAQUE is a strong dPAKE (sdPAKE).
* Replaced "secure aPAKE" with "strong dPAKE" (sdPAKE). Strong being what academic papers use to describe PAKEs that are secure against pre-computation attacks.
The following might need to be reworded or use a different source. Since JKX18 defined an saPAKE vs sdPAKE. The difference being that the client can also store data that can be used to authenticate to the server but not used to authenticate to the client. Lines 325-326:
> \- This document describes OPAQUE, an aPAKE that is secure against pre-computation attacks (as defined in {{JKX18}}).
> \+ This document describes OPAQUE, an sdPAKE (as …

OPAQUE is an sdPAKE

---

draft-irtf-cfrg-opaque.md

This PR adds a clarifying note that the original OPAQUE protocol described a 2-message protocol, but the one presented in this draft is a 3-message version. This is under the "Notable Design Differences" section.
It also adds a reference to the full version of the OPAQUE paper (https://eprint.iacr.org/2018/163) where the 3-message protocol is analyzed.

Adding distinction between 3-message and 2-message protocol in design differences section

---

draft-irtf-cfrg-opaque.md

We are adding a caveat to the original text,
"The `oprf_seed` value SHOULD be used for all clients; see {{preventing-client-enumeration}}."
The reason being that the leakage of this global value would compromise security for all users that depend on this value, and one could arguably improve security of the protocol against this kind of compromise by sampling independent OPRF keys. However, we still keep the recommendation to use the global seed value in this way in favor of protecting against client enumeration attacks.
But, applications that don't care about preventing client enumeration can feel free to use independently-sampled OPRF keys.

Adding comment which caveats OPRF seed usage

---

draft-irtf-cfrg-opaque.md

Adding some text to the Implementation Considerations section, by creating a subsection called "Handling Online Guessing Attacks", and highlighting the fact that servers should treat incomplete AKE interactions (after client receives KE2) as authentication failures by default.

Adding note on handling online guessing attacks

---

.github/workflows/archive.yml

See https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
Hopefully this should fix the CI

Updating upload artifact action version

---

.github/workflows/archive.yml
.github/workflows/ghpages.yml

Also updating action version in ghpages (should have been a part of #461)
Reverting to v3 since v4 introduces a breaking change

Also updating action version in ghpages

---

draft-irtf-cfrg-opaque.md

Adding a sentence to the end of the Introduction to say “This document is not an IETF product and is not a standard” to meet the requirements of RFC 5743.

Adding IETF note for RFC5743

---

draft-irtf-cfrg-opaque.md

Some of the APIs reference specific sections of RFC 9497, some do not. This PR ensures that we consistently reference RFC 9497 in cases when the APIs are defined there

Normalize RFC9497 references

---

draft-irtf-cfrg-opaque.md

Instead of the using the syntax
```
Create Envelope envelope with (envelope_nonce, auth_tag)
```
in pseudocode, we now say:
```
envelope = Envelope {
envelope_nonce,
auth_tag
}
```
This is done for all of the instantiated structs in the protocol.
Also, we are renaming the `nonce` field of an `Envelope` to be called `envelope_nonce`, as this will match the protocol and test vectors.

Fixing constructors for structs in pseudocode

---

draft-irtf-cfrg-opaque.md

Two small edits:
1) The Expand interface as used in the protocol always has the info string supplied. I edited the text and removed the word “optional” to make this more clear
2) For clarity, changing “The registration flow is shown below” to “The registration message flow is shown below and the process is described in detail in Section 5”.

Incorporating minor editorial clarifications

---

draft-irtf-cfrg-opaque.md

There was a mismatch between the definition of FinalizeRegistrationRequest, and its representation in the protocol diagram. This adds the missing parameters (password, blind) to the diagram.

Fixing FinalizeRegistrationRequest diagram API

---

draft-irtf-cfrg-opaque.md

See https://mailarchive.ietf.org/arch/msg/cfrg/dkobloepKBl8kmpcyMb71rX03ms/
And the responses:
1. Updated
2. Updated
3. Changed, but simply removed the word “hence” instead of adding a comma between “hence” and “determined”
4. Added notes that “This is equivalent to the Blind/Finalize function described in Section 3.3.1 of {{RFC9497}}.”
5. Updated
6. I think that how the session_key gets used as the output of the key exchange is outside the scope of this document. We added clarification for the usage of export_key because it is an atypical output for key exchange, but we expect session_key to be more well-understood. Additionally, it is difficult to arrive at a consensus for how session_key is used, since it is likely to be application-specific. However, unless others chime in with the …

Addressing comments from ISRG review

---

draft-irtf-cfrg-opaque.md

Adding missing encodings for CleartextCredentials and CustomLabel
